# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-23 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FName', models.CharField(max_length=250)),
                ('SName', models.CharField(max_length=250)),
                ('Stagename', models.CharField(max_length=250)),
                ('Band', models.CharField(max_length=250)),
                ('Genre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('What', models.CharField(max_length=2500)),
                ('When', models.DateField(blank=True, null=True)),
                ('How', models.CharField(max_length=2500)),
                ('Who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Year', models.DateField(blank=True, null=True)),
                ('Band', models.CharField(max_length=250)),
                ('Genre', models.CharField(max_length=250)),
                ('Stagename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('What', models.CharField(max_length=2500)),
                ('When', models.DateField(blank=True, null=True)),
                ('How', models.CharField(max_length=2500)),
                ('Who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent', models.CharField(choices=[('pr', 'Painter'), ('mu', 'Musician'), ('dp', 'Performance'), ('pt', 'Poet/RAP'), ('ph', 'Photography'), ('an', 'Animation'), ('at', 'Architecture'), ('cr', 'Computer'), ('ce', 'Ceramics'), ('ca', 'Calligraphy'), ('ag', 'Assemblage'), ('dr', 'Drawing'), ('gi', 'Graffiti'), ('gr', 'Graphic'), ('il', 'Illustration'), ('mo', 'Mosaic'), ('sc', 'Sculpture'), ('vr', 'Videographer')], max_length=3)),
                ('Stagename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Artist')),
            ],
        ),
    ]
