# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-12 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crafts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=250)),
                ('artist_type', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=250)),
                ('work_image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Song_MasterPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=50)),
                ('work_title', models.CharField(max_length=250)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Crafts')),
            ],
        ),
    ]
