# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-25 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='sname',
        ),
    ]
