# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-14 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Craft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('craft_artist', models.CharField(max_length=250)),
                ('craft_Title', models.CharField(max_length=500)),
                ('craft_Type', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=250)),
                ('work_Image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_media', models.CharField(max_length=250)),
                ('work_title', models.CharField(max_length=250)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Craft')),
            ],
        ),
        migrations.RemoveField(
            model_name='song_masterpiece',
            name='collection',
        ),
        migrations.DeleteModel(
            name='Crafts',
        ),
        migrations.DeleteModel(
            name='Song_MasterPiece',
        ),
    ]
