# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-14 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_auto_20190414_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
