# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-17 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_bug_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogue',
            old_name='catalogue_title',
            new_name='title',
        ),
    ]
