# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-14 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_work_is_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='craft',
            old_name='craft_Title',
            new_name='craft_title',
        ),
        migrations.RenameField(
            model_name='craft',
            old_name='craft_Type',
            new_name='craft_type',
        ),
        migrations.RenameField(
            model_name='craft',
            old_name='work_Image',
            new_name='work_image',
        ),
    ]
