# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-26 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_auto_20190525_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
