# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-16 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_auto_20190516_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craft',
            name='talent',
            field=models.CharField(choices=[('par', 'Painter'), ('mus', 'Musician'), ('drp', 'Performance'), ('ptr', 'Poet/RAP'), ('pho', 'Photography'), ('ani', 'Animation'), ('ate', 'Architecture'), ('cpr', 'Computer'), ('cer', 'Ceramics'), ('cal', 'Calligraphy'), ('asg', 'Assemblage'), ('drw', 'Drawing'), ('gri', 'Graffiti'), ('gra', 'Graphic'), ('ill', 'Illustration'), ('mos', 'Mosaic'), ('scu', 'Sculpture'), ('vgr', 'Videographer')], max_length=3),
        ),
    ]
