# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-16 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_auto_20190414_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='work',
            new_name='work_id',
        ),
    ]
