# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-26 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0006_artform_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='cover_Image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
