# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-16 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0006_auto_20190516_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='file',
            field=models.FileField(default=1, upload_to='songs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(default=1, upload_to='songs/'),
            preserve_default=False,
        ),
    ]
