# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-26 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0007_catalogue_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artform',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Artist'),
        ),
    ]
