# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-17 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0007_remove_craft_craft_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='craft',
            old_name='work_image',
            new_name='craft_logo',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='work_id',
            new_name='craft',
        ),
    ]
