# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-16 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0008_auto_20190516_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'artist', 'verbose_name_plural': 'artists'},
        ),
        migrations.AlterModelOptions(
            name='bug',
            options={'verbose_name': 'bug', 'verbose_name_plural': 'bugs'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'feature', 'verbose_name_plural': 'features'},
        ),
    ]
