# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-20 10:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0009_auto_20190417_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='craft',
            name='bug',
            field=models.CharField(default=datetime.datetime(2019, 4, 20, 10, 30, 48, 684640, tzinfo=utc), max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='craft',
            name='feature',
            field=models.CharField(default=datetime.datetime(2019, 4, 20, 10, 32, 7, 69446, tzinfo=utc), max_length=3000),
            preserve_default=False,
        ),
    ]
