# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-16 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0010_auto_20190516_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='user',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='band',
            name='Members',
        ),
        migrations.AddField(
            model_name='band',
            name='Member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artist.Artist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='Band',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='artist',
            name='FName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Genre',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='artist',
            name='SName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Stagename',
            field=models.CharField(max_length=50),
        ),
    ]
