# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-16 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0011_auto_20190516_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Year', models.DateField(blank=True, null=True)),
                ('Genre', models.CharField(max_length=10)),
                ('cover', models.ImageField(upload_to='images/')),
                ('file', models.FileField(upload_to='files/')),
                ('Stagename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Artist')),
            ],
            options={
                'verbose_name': 'other_Art',
                'verbose_name_plural': 'other_Arts',
            },
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Year', models.DateField(blank=True, null=True)),
                ('Genre', models.CharField(max_length=10)),
                ('cover', models.ImageField(upload_to='images/')),
                ('file', models.FileField(upload_to='files/')),
                ('Stagename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Artist')),
            ],
            options={
                'verbose_name': 'painting',
                'verbose_name_plural': 'paintings',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Year', models.DateField(blank=True, null=True)),
                ('Genre', models.CharField(max_length=10)),
                ('cover', models.ImageField(upload_to='images/')),
                ('file', models.FileField(upload_to='songs/')),
                ('Stagename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Artist')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
            },
        ),
        migrations.AddField(
            model_name='song',
            name='catalogue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artist.Catalogue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='band',
            name='Stagename',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='beat',
            name='Genre',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='beat',
            name='Title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='Band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Band'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='Title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='Genre',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='song',
            name='Title',
            field=models.CharField(max_length=50),
        ),
    ]
