# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-20 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0011_auto_20190420_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artist', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=500)),
                ('crafts', models.TextField(max_length=5000)),
                ('genre', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='craft',
            name='genre',
        ),
    ]
